### ISSUE TITLE
scattering time step issue

### ISSUE THREAD

**Issue by walkerna22** [lazzati-astro/MCRaT#1]
photon scattering times are compared to the total time between hydro frames, instead of the remaining time in the current frame.  This can cause photons to travel farther than they should in certain situations

**Comment by parsotat** [comment]
Commit 362f587  should address this issue, please use that to verify that the issue has been resolved in the 16TI simulation and feel free to include your verification results here, comparing the old MCRaT results with the new (corresponding to the referenced commit) MCRaT results of the 16TI code.

**Comment by walkerna22** [comment]
I ran the requested validation using that commit and the results agree with past MCRaT runs.  The attached lightcurves and spectra agree with previously published results (the Ye=0.1 run in this paper https://iopscience.iop.org/article/10.3847/1538-4357/ad2dfa).  

![s_validate](https://github.com/lazzati-astro/MCRaT/assets/4551626/d4b91a98-346f-4b65-8188-494fb4649576)
![lc_validate](https://github.com/lazzati-astro/MCRaT/assets/4551626/b6748ed7-c9c0-4f41-af04-c85cf026e05d)

**Comment by parsotat** [comment]
This is great @walkerna22. thanks for running this software verification. I will go ahead and close this issue now.
